# Generated by Django 2.0.7 on 2018-08-29 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180823_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposits',
            name='active',
        ),
        migrations.RemoveField(
            model_name='deposits',
            name='cummulated_interest',
        ),
        migrations.RemoveField(
            model_name='deposits',
            name='months_paid',
        ),
        migrations.RemoveField(
            model_name='deposits',
            name='quantity',
        ),
    ]
